apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-egcl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-egcl
    app.kubernetes.io/part-of: ci10t-776-0020-app
  name: devfile-sample-egcl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-egcl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-egcl
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0020-tenant/ci10t-776-0020-app/devfile-sample-egcl@sha256:f8b6bb956b4893276d7002134d1043f63276964d111695063743cb23265fab8a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
